### ISSUE TITLE
travis-ciでphpmd発火

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Videos#11]
### 　エラー

https://travis-ci.org/NetCommons3/Videos/jobs/65526385

```
/home/travis/build/NetCommons3/NetCommons3/app/Plugin/Videos/Model/Video.php:21 The class Video has an overall complexity of 53 which is very high. The configured complexity threshold is 50.

/home/travis/build/NetCommons3/NetCommons3/app/Plugin/Videos/Model/Video.php:132    The method beforeValidate() has 134 lines of code. Current threshold is set to 100. Avoid really long methods.
```
### 対応

Video.php のリファクタリングを予定

**Comment by akagane99** [comment]
対応済み

https://github.com/NetCommons3/Videos/commit/7806243faba3d4fd597011322a8f8de16e3d21e4
https://github.com/NetCommons3/Videos/commit/253b6cf0499318a2cfc34ef034ee73a471cce1ab

**Comment by s-nakajima** [comment]
既にご存知かもしれませんが、開発環境でphpmdを動かしたら、phpmdエラーがでました。

/var/www/app/app/Plugin/Videos/Model/Video.php:21   The class Video has an overall complexity of 52 which is very high. The configured complexity threshold is 50.

**Comment by akagane99** [comment]
指摘サンキュー。
travicでも発火してた。
のちのち対応します。

**Comment by akagane99** [comment]
大幅なリファクタリング中で、ほぼ元のソースが変わっているため、本件は一旦クローズする。
傾向としては、コード量が減りつつあるので、ほぼ解消する見込み。
