### ISSUE TITLE
Filesプラグインに同等機能が実装される想定

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Videos#12]
Filesプラグインに同等機能が実装される想定
https://github.com/NetCommons3/Videos/blob/master/Model/Behavior/VideoFileBehavior.php
https://github.com/NetCommons3/Videos/blob/master/View/Elements/VideosEdit/file.ctp

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Videos/blob/master/View/Elements/VideosEdit/file.ctp
について$fieldの扱いとしては、モデル名が分かりやすいので、Filesに持っていく際直しましょう。

**Comment by akagane99** [comment]
Files全面見直しにより、クローズ
