### ISSUE TITLE
再生時間について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Videos#29]
https://github.com/NetCommons3/Videos/blob/master/Model/Video.php#L210

使っていないような気がします。

また、TimeHelperは使えないでしょうか？
Viewファイルで、
$this->Time->format('H:i', $Video['video_time'])
みたいな感じで取得できる気がします。
結果、VideoBehavior::convSecToHourはいらないと思われます。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L146

使ってますね。

https://github.com/NetCommons3/Videos/blob/master/Model/Behavior/VideoBehavior.php#L251
TimeHelperで上記と同等の事ができるのであれば、代用可能だと思います。

http://book.cakephp.org/2.0/ja/core-libraries/helpers/time.html
公式ドキュメントを見ても、秒表示、ゼロ埋めが出来るのか、よくわからなかったです。

**Comment by kteraguchi** [comment]
$video['video']['videoTimeView']使用の件了解です。
camelize忘れてました。。。video_time_viewで検索しヒットしなかったもので。申し訳ないです。

> 公式ドキュメントを見ても、秒表示、ゼロ埋めが出来るのか、よくわからなかったです。

$this->Time->format('H:i:s', $video['video']['videoTime'])
でいけるかと思ったのですが、60分未満でも00時が表示されちゃうのでダメでした。
VideoBehavior::convSecToHourはいりますね。
処理としてはHelperが良いと思います。

**Comment by akagane99** [comment]
> 処理としてはHelperが良いと思います。

なるほど了解です。下記Helperを参考に対応します。
https://github.com/NetCommons3/NetCommons/tree/master/View/Helper

対応時期は、コントローラーのテストが完了してから対応しようと思います。
