### ISSUE TITLE
Video::ffmpegEnableについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Videos#30]
Video::beforeValidateが呼び出されるまでは、Video::ffmpegEnableはデフォルトのtrueが設定されています。
誤解を招くので、ffmpegが有効かの判断は、VideoBehavior::isFfmpegEnableを呼び出す方が良いと思います。
Page::isSettingが参考になると思います。

**Comment by akagane99** [comment]
おす。下記参考にします。

https://github.com/NetCommons3/Pages/blob/7604f7f03675e144a0adb5c15fa9a13cb0b94d8c/Model/Page.php#L34-L39
https://github.com/NetCommons3/Pages/blob/7604f7f03675e144a0adb5c15fa9a13cb0b94d8c/Model/Page.php#L210-L228

**Comment by akagane99** [comment]
対応してみた。

**Comment by akagane99** [comment]
開発環境でナカジshell( https://github.com/s-nakajima/MyShell/blob/master/nc3PluginTest/nc3PluginTest.sh )で phpmd走らせると以下エラーが出ました。

```
##################################
PHP Mess Detector(phpmd)
##################################
/var/www/app/vendors/bin/phpmd app/Plugin/Videos text /etc/phpmd/rules.xml

/var/www/app/app/Plugin/Videos/Model/Video.php:85       Avoid unused private fields such as '$__isFfmpegEnable'.
```

self::$__isFfmpegEnableでセットしたり、参照してるのに、Avoid unused private fields such（このプライベートフィールド使ってないよ）とエラーがでる謎。

8/15時点のpagesもphpmd走らせると、同じエラーが出てました。

```
##################################
PHP Mess Detector(phpmd)
##################################
/var/www/app/vendors/bin/phpmd app/Plugin/Pages text /etc/phpmd/rules.xml

/var/www/app/app/Plugin/Pages/Model/Page.php:39 Avoid unused private fields such as '$__isSetting'.
/var/www/app/app/Plugin/Pages/View/Helper/PageLayoutHelper.php:40       Avoid unused private fields such as '$__containers'.
/var/www/app/app/Plugin/Pages/View/Helper/PageLayoutHelper.php:47       Avoid unused private fields such as '$__boxes'.
/var/www/app/app/Plugin/Pages/View/Helper/PageLayoutHelper.php:54       Avoid unused private fields such as '$__plugins'.
/var/www/app/app/Plugin/Pages/View/Helper/PageLayoutHelper.php:61       Avoid unused private fields such as '$__pluginMap'.
```

travis-ciのPagesではエラー出てないですね。
https://travis-ci.org/NetCommons3/Pages

@kteraguchi 開発環境ではphpmdでエラーでるけど、対応はこのままで良いですよね？
もくもく会の時にでも回答ください。

**Comment by kteraguchi** [comment]
これかもです。
https://github.com/NetCommons3/NetCommons/issues/6

/home/vagrant/.pdependにあるキャシュファイルのユーザー、および、パーミッションを確認してみてください。

**Comment by akagane99** [comment]
！！
ほんとだ`/home/vagrant/.pdepend` のオーナー `root` でした。
`sudo chown -R vagrant. /home/vagrant` で解消しました。
感謝！
