### ISSUE TITLE
動画登録処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Videos#31]
ffmpegが有効か否かで登録処理が分かれていますが、一緒にした方が良い気がしています。
ファイルアップロード処理も絡んでいるため、追い切れていないです。
もくもく会で相談させてください。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Videos/blob/0cf1c4b4f0fcb8f2320d6129e751234fa72d4979/Model/Video.php#L245-L253
https://github.com/NetCommons3/Videos/blob/0cf1c4b4f0fcb8f2320d6129e751234fa72d4979/Model/Video.php#L318-L325

をbeforesaveとかで１本にまとめる。

β対応。

**Comment by akagane99** [comment]
現状のままにする。
アップロードプラグインができるまで保留とする

**Comment by akagane99** [comment]
対応しました。
git pushしたけどgithubの障害で、反映見えない感じです。
多分、数日後には解消していると思いますので、クローズします。

**Comment by akagane99** [comment]
github反映されました。
