### ISSUE TITLE
Viewファイルのインデント

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Videos#33]
4スペースが混在しています。
CakePHP2はタブらしいのでタブで合わせましょう。

CakePHP3はPSR準拠で4スペースですね。

**Comment by akagane99** [comment]
対応しました。

**Comment by akagane99** [comment]
@s-nakajima に修正してもらった箇所。
- Travisではエラーにしていないが、本来phpcs エラーであるため修正  https://github.com/NetCommons3/Videos/commit/ae44fe4b7783dccce0917bb6350f5f24b1fba1a4

@kteraguchi レビューで指摘あり、1度修正した箇所なんです。
- ナカジshell（ https://github.com/s-nakajima/MyShell/blob/master/nc3PluginTest/nc3PluginTest.sh ）でphpcsを走らせるとエラー。
- Travisではphpcsエラーにならない。

というずれた状態になってる。
どちらでも良いと思うので、合わせたいよね。

@s-nakajima , @kteraguchi  次回もくもく会で相談のってください。

**Comment by akagane99** [comment]
@s-nakajima より教えてもらった。
- レビューの指摘は、タブでネストする所を、スペースでネストしていたから直してね。という事。
- 「特別な修正はしてなくって、タグのネストを合わせただけ」との事。

改めて修正ファイルを確認したら、確かにその通りだった。
https://github.com/NetCommons3/Videos/blob/ae44fe4b7783dccce0917bb6350f5f24b1fba1a4/View/Videos/index.ctp

なるほど、`<?php>`も`<?php else : ?>`上部のコメントも、全部ネストするのか。

理解できたので、クローズします。
