### ISSUE TITLE
チャンネル登録（ブロック設定）でNotice

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Videos#6]
チャンネル名を未入力で決定ボタンをクリックすると、Noticeがでる。

（クリック前）
![default](https://cloud.githubusercontent.com/assets/4422735/7978490/caeab514-0ad0-11e5-8f80-c018c4082fc4.PNG)

（決定ボタンクリック）
![default](https://cloud.githubusercontent.com/assets/4422735/7978468/9f8da3c2-0ad0-11e5-88e5-648f3c59ac91.PNG)

**Comment by akagane99** [comment]
報告感謝。
対応しました。
