### ISSUE TITLE
動画時間の入力がテキストボックスになっている

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Videos#7]
動画時間は、数値型なのでtype=numberにするか、もしくは、時間なので固定のセレクトボックスでも良いと思う。type=numberにする場合は、Iframeを参考に。。。

https://github.com/NetCommons3/Iframes/blob/master/View/Elements/IframeBlocks/edit_form.ctp#L72-L81

**Comment by akagane99** [comment]
ご指摘感謝

**Comment by akagane99** [comment]
動画時間の時：分：秒入力のため、独自対応しました。

https://github.com/NetCommons3/Videos/blob/f8f54947075bde062439bf9ee56615a31e4fa9ac/View/VideosEdit/add.ctp#L78
https://github.com/NetCommons3/Videos/blob/f8f54947075bde062439bf9ee56615a31e4fa9ac/View/VideosEdit/edit.ctp#L60
https://github.com/NetCommons3/Videos/commit/f8f54947075bde062439bf9ee56615a31e4fa9ac#diff-4dead8629cf00b4205800957eea85ceaR328
https://github.com/NetCommons3/Videos/commit/f8f54947075bde062439bf9ee56615a31e4fa9ac#diff-4dead8629cf00b4205800957eea85ceaR377
