### ISSUE TITLE
Chromeだと、真っ白の状態で表示される。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Videos#8]
Chromeだと、真っ白の状態で表示される。ただ、▶（再生）をクリックするとちゃんと再生される。
こういうもの？？

![default](https://cloud.githubusercontent.com/assets/4422735/7979108/6e4eaa98-0ad7-11e5-9dcd-cbafce4cabf3.PNG)

**Comment by akagane99** [comment]
ffmpeg = falseで、サムネイル未登録だと、どのブラウザでも上記の表示通りです。

validateの実装がまだなので、サムネイルを登録すれば表示されるでしょう。
