### ISSUE TITLE
ブロック一覧の「#」を消してください。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Videos#9]
すみません。当初、掲示板やFAQのブロック一覧に「#」があったのですが、先生が「#」を付けないでほしいとのことで、全体的に「#」を削除しています。そのため、動画プラグインもブロック一覧の「#」を消してください。

![default](https://cloud.githubusercontent.com/assets/4422735/7979280/d9a2e72c-0ad8-11e5-8756-a0d0ed9c8519.PNG)

**Comment by akagane99** [comment]
thx
